import { State, Lab, AppNotification, Language } from './types';

export const LOGO_URL = "https://raw.githubusercontent.com/Anand-Mishra-dev/Anand-Mishra-dev/refs/heads/main/volunteer-logo.png";

export const BRAND_COLORS = {
  deepBlue: "#1A005B",
  teal: "#007DA5",
  gradient: "linear-gradient(135deg, #1A005B 0%, #007DA5 100%)",
  radialGradient: "radial-gradient(circle at center, #007DA5 0%, #1A005B 100%)"
};

export const LANGUAGES: { code: Language; label: string }[] = [
  { code: 'EN', label: 'English' },
  { code: 'HI', label: 'हिंदी' },
  { code: 'MR', label: 'मराठी' },
  { code: 'GU', label: 'ગુજરાતી' },
  { code: 'TE', label: 'తెలుగు' },
  { code: 'TA', label: 'தமிழ்' },
  { code: 'KN', label: 'ಕನ್ನಡ' }
];

export const TRANSLATIONS: Record<Language, any> = {
  EN: {
    welcome: "Welcome Back",
    signIn: "Sign in to your account",
    login: "Login",
    signup: "Sign Up",
    forgotPass: "Forgot Password?",
    asVolunteer: "As Volunteer",
    asAdmin: "As Admin",
    createAccount: "Create Identity",
    mobile: "Mobile Number",
    password: "Password",
    explore: "Explore by State",
    notifications: "Intelligence Feed",
    adminDashboard: "Admin Dashboard",
    addHub: "Add Facility Hub",
    updateDetail: "Update Details",
    name: "Name",
    surname: "Surname",
    sendOtp: "Send OTP",
    verify: "Verify",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    dob: "Date of Birth",
    email: "Email",
    confirmPass: "Confirm Password",
    submit: "Submit",
    resetPass: "Reset Password",
    backToLogin: "Back to Login",
    enterMobile: "Enter registered mobile number",
    otpSent: "OTP Sent",
    liveStatus: "Live Status",
    allDetails: "All Details",
    facilities: "Facilities",
    amount: "Amount",
    view: "View",
    contact: "Contact",
    contactPerson: "Contact Person",
    contactNumber: "Contact Number",
    call: "Call",
    directions: "Get Directions"
  },
  HI: {
    welcome: "वापसी पर स्वागत है",
    signIn: "अपने खाते में साइन इन करें",
    login: "लॉगिन",
    signup: "साइन अप करें",
    forgotPass: "पासवर्ड भूल गए?",
    asVolunteer: "स्वयंसेवक के रूप में",
    asAdmin: "एडमिन के रूप में",
    createAccount: "पहचान बनाएं",
    mobile: "मोबाइल नंबर",
    password: "पासवर्ड",
    explore: "राज्य अनुसार खोजें",
    notifications: "सूचनाएं",
    adminDashboard: "एडमिन डैशबोर्ड",
    addHub: "सुविधा केंद्र जोड़ें",
    updateDetail: "विवरण अपडेट करें",
    name: "नाम",
    surname: "उपनाम",
    sendOtp: "ओटीपी भेजें",
    verify: "सत्यापित करें",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    dob: "जन्म तिथि",
    email: "ईमेल",
    confirmPass: "पासवर्ड की पुष्टि करें",
    submit: "जमा करें",
    resetPass: "पासवर्ड रीसेट करें",
    backToLogin: "लॉगिन पर वापस जाएं",
    enterMobile: "पंजीकृत मोबाइल नंबर दर्ज करें",
    otpSent: "ओटीपी भेजा गया",
    liveStatus: "लाइव स्थिति",
    allDetails: "सभी विवरण",
    facilities: "सुविधाएं",
    amount: "राशि",
    view: "देखें",
    contact: "संपर्क",
    contactPerson: "संपर्क व्यक्ति",
    contactNumber: "संपर्क नंबर",
    call: "कॉल करें",
    directions: "दिशा प्राप्त करें"
  },
  MR: {
    welcome: "पुन्हा स्वागत आहे",
    signIn: "आपल्या खात्यात साइन इन करा",
    login: "लॉगिन",
    signup: "साइन अप करा",
    forgotPass: "पासवर्ड विसरलात?",
    asVolunteer: "स्वयंसेवक म्हणून",
    asAdmin: "ॲडमिन म्हणून",
    createAccount: "ओळख निर्माण करा",
    mobile: "मोबाईल नंबर",
    password: "पासवर्ड",
    explore: "राज्यानुसार शोधा",
    notifications: "सूचना",
    adminDashboard: "ॲडमिन डॅशबोर्ड",
    addHub: "सुविधा केंद्र जोडा",
    updateDetail: "तपशील अपडेट करा",
    name: "नाव",
    surname: "आडनाव",
    sendOtp: "OTP पाठवा",
    verify: "पडताळणी करा",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "इतर",
    dob: "जन्म तारीख",
    email: "ईमेल",
    confirmPass: "पासवर्डची पुष्टी करा",
    submit: "सादर करा",
    resetPass: "पासवर्ड रीसेट करा",
    backToLogin: "लॉगिनवर परत जा",
    enterMobile: "नोंदणीकृत मोबाईल नंबर टाका",
    otpSent: "OTP पाठवला",
    liveStatus: "थेट स्थिती",
    allDetails: "सर्व तपशील",
    facilities: "सुविधा",
    amount: "रक्कम",
    view: "पहा",
    contact: "संपर्क",
    contactPerson: "संपर्क व्यक्ती",
    contactNumber: "संपर्क क्रमांक",
    call: "कॉल करा",
    directions: "ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಿರಿ" 
  },
  GU: {
    welcome: "સ્વાગત છે",
    signIn: "તમારા ખાતામાં લોગ ઇન કરો",
    login: "લોગિન",
    signup: "સાઇન અપ કરો",
    forgotPass: "પાસવર્ડ ભૂલી ગયા છો?",
    asVolunteer: "સ્વયંસેવક તરીકે",
    asAdmin: "એડમિન તરીકે",
    createAccount: "ઓળખ બનાવો",
    mobile: "મોબાઈલ નંબર",
    password: "પાસવર્ડ",
    explore: "રાજ્ય મુજબ શોધો",
    notifications: "સૂચનાઓ",
    adminDashboard: "એડમિન ડેશબોર્ડ",
    addHub: "સુવિધા કેન્દ્ર ઉમેરો",
    updateDetail: "વિગતો અપડેટ કરો",
    name: "નામ",
    surname: "અટક",
    sendOtp: "OTP મોકલો",
    verify: "ચકાસો",
    gender: "લિંગ",
    male: "પુરુષ",
    female: "સ્ત્રી",
    other: "અન્ય",
    dob: "જન્મ તારીખ",
    email: "ઇમેઇલ",
    confirmPass: "પાસવર્ડ પુષ્ટિ કરો",
    submit: "સબમિટ કરો",
    resetPass: "પાસવર્ડ રીસેટ કરો",
    backToLogin: "લોગિન પર પાછા જાઓ",
    enterMobile: "રજિસ્ટર્ડ મોબાઇલ નંબર દાખલ કરો",
    otpSent: "OTP મોકલ્યો",
    liveStatus: "લાઇવ સ્ટેટસ",
    allDetails: "બધી વિગતો",
    facilities: "સુવિધાઓ",
    amount: "રકમ",
    view: "જુઓ",
    contact: "સંપર્ક",
    contactPerson: "સંપર્ક વ્યક્તિ",
    contactNumber: "સંપર્ક નંબર",
    call: "કોલ કરો",
    directions: "દિશાઓ મેળવો"
  },
  TE: {
    welcome: "స్వాగతం",
    signIn: "మీ ఖాతాకు సైన్ ఇన్ చేయండి",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    forgotPass: "పాస్‌వర్డ్ మర్చిపోయారా?",
    asVolunteer: "వాలంటీర్‌గా",
    asAdmin: "అడ్మిన్‌గా",
    createAccount: "గుర్తింపును సృష్టించండి",
    mobile: "మొబైల్ నంబర్",
    password: "పాస్‌వర్డ్",
    explore: "రాష్ట్రం ప్రకారం అన్వేషించండి",
    notifications: "నోటిఫికేషన్లు",
    adminDashboard: "అడ్మిన్ డాష్‌బోర్డ్",
    addHub: "సౌకర్యాన్ని జోడించండి",
    updateDetail: "వివరాలను నవీకరించండి",
    name: "పేరు",
    surname: "ఇంటిపేరు",
    sendOtp: "OTP పంపండి",
    verify: "ధృవీకరించండి",
    gender: "లింగం",
    male: "పురుషుడు",
    female: "స్త్రీ",
    other: "ఇతర",
    dob: "పుట్టిన తేదీ",
    email: "ఇమెయిల్",
    confirmPass: "పాస్‌వర్డ్ నిర్ధారించండి",
    submit: "సమర్పించు",
    resetPass: "పాస్‌వర్డ్ రీసెట్",
    backToLogin: "లాగిన్‌కి తిరిగి వెళ్లు",
    enterMobile: "రిజిస్టర్డ్ మొబైల్ నంబర్ నమోదు చేయండి",
    otpSent: "OTP పంపబడింది",
    liveStatus: "లైవ్ స్థితి",
    allDetails: "అన్ని వివరాలు",
    facilities: "సౌకర్యాలు",
    amount: "మొత్తం",
    view: "చూడండి",
    contact: "సంప్రదించండి",
    contactPerson: "సంప్రదింపు వ్యక్తి",
    contactNumber: "సంప్రదింపు సంఖ్య",
    call: "కాల్ చేయండి",
    directions: "దిశలను పొందండి"
  },
  TA: {
    welcome: "வரவேற்கிறோம்",
    signIn: "உங்கள் கணக்கில் உள்நுழையவும்",
    login: "உள்நுழை",
    signup: "பதிவு செய்க",
    forgotPass: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    asVolunteer: "தன்னார்வலராக",
    asAdmin: "நிர்வாகியாக",
    createAccount: "அடையாளத்தை உருவாக்கவும்",
    mobile: "கைபேசி எண்",
    password: "கடவுச்சொல்",
    explore: "மாநில வாரியாக ஆராயுங்கள்",
    notifications: "அறிவிப்புகள்",
    adminDashboard: "நிர்வாக டாஷ்போர்டு",
    addHub: "வசதியைச் சேர்க்கவும்",
    updateDetail: "விவரங்களைப் புதுப்பிக்கவும்",
    name: "பெயர்",
    surname: "குடும்பப் பெயர்",
    sendOtp: "OTP அனுப்பு",
    verify: "சரிபார்",
    gender: "பாலினம்",
    male: "ஆண்",
    female: "பெண்",
    other: "மற்றவை",
    dob: "பிறந்த தேதி",
    email: "மின்னஞ்சல்",
    confirmPass: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    submit: "சமர்ப்பிக்கவும்",
    resetPass: "கடவுச்சொல்லை மீட்டமைக்கவும்",
    backToLogin: "உள்நுழைவுக்குத் திரும்பு",
    enterMobile: "பதிவுசெய்யப்பட்ட மொபைல் எண்ணை உள்ளிடவும்",
    otpSent: "OTP அனுப்பப்பட்டது",
    liveStatus: "நேரலை நிலை",
    allDetails: "அனைத்து விவரங்கள்",
    facilities: "வசதிகள்",
    amount: "தொகை",
    view: "பார்வை",
    contact: "தொடர்பு",
    contactPerson: "தொடர்பு நபர்",
    contactNumber: "தொடர்பு எண்",
    call: "அழைப்பு",
    directions: "திசைகளைப் பெறுக"
  },
  KN: {
    welcome: "ಸ್ವಾಗತ",
    signIn: "ನಿಮ್ಮ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ",
    login: "ಲಾಗಿನ್",
    signup: "ಸೈನ್ ಅಪ್",
    forgotPass: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    asVolunteer: "ಸ್ವಯಂಸೇವಕರಾಗಿ",
    asAdmin: "ನಿರ್ವಾಹಕರಾಗಿ",
    createAccount: "ಗುರುತನ್ನು ರಚಿಸಿ",
    mobile: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    password: "ಪಾಸ್ವರ್ಡ್",
    explore: "ರಾಜ್ಯವಾರು ಅನ್ವೇಷಿಸಿ",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    adminDashboard: "ನಿರ್ವಾಹಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    addHub: "ಸೌಲಭ್ಯವನ್ನು ಸೇರಿಸಿ",
    updateDetail: "ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ",
    name: "ಹೆಸರು",
    surname: "ಉಪನಾಮ",
    sendOtp: "OTP ಕಳುಹಿಸಿ",
    verify: "ಪರಿಶೀಲಿಸಿ",
    gender: "ಲಿಂಗ",
    male: "ಪುರುಷ",
    female: "ಮಹಿಳೆ",
    other: "ಇತರೆ",
    dob: "ಜನ್ಮ ದಿನಾಂಕ",
    email: "ಇಮೇಲ್",
    confirmPass: "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
    submit: "ಸಲ್ಲಿಸಿ",
    resetPass: "ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ",
    backToLogin: "ಲಾಗಿನ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    enterMobile: "ನೋಂದಾಯಿತ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    otpSent: "OTP ಕಳುಹಿಸಲಾಗಿದೆ",
    liveStatus: "ಲೈವ್ ಸ್ಥಿತಿ",
    allDetails: "ಎಲ್ಲಾ ವಿವರಗಳು",
    facilities: "ಸೌಲಭ್ಯಗಳು",
    amount: "ಮೊತ್ತ",
    view: "ವೀಕ್ಷಿಸಿ",
    contact: "ಸಂಪರ್ಕಿಸಿ",
    contactPerson: "ಸಂಪರ್ಕ ವ್ಯಕ್ತಿ",
    contactNumber: "ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
    call: "ಕರೆ ಮಾಡಿ",
    directions: "ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಿರಿ"
  }
};

export const STATES_LIST = [
  State.Maharashtra, State.Gujarat, State.Telangana, State.Karnataka,
  State.AndhraPradesh, State.TamilNadu, State.Delhi, State.Goa
];

export const MOCK_LABS: Lab[] = [
  {
    id: '1',
    name: 'Clinovi Research',
    state: State.Maharashtra,
    status: 'Active',
    detail: 'CLINOVI',
    report: 'Screening Open',
    contact: 'Dr. Screen',
    phone: '+91 9876543210',
    volunteerGender: 'Male Only',
    inHouse: '72 Hours',
    periodCount: '3',
    condition: 'Fasting/Fed',
    lossMl: '357 mL',
    ambulatory: 'No',
    bmi: '19.5 to 30',
    age: '18 to 44',
    amount: '₹ 15,000',
    period1: '20-01-2026',
    period2: '27-01-2026',
    period3: '03-02-2026',
    period4: 'None',
    screeningDate: '16/01/2026 to 19/01/2026',
    screeningTime: '07:30 to 10:30',
    requirements: 'Original Aadhar card, PAN Card compulsory\nScreening date 16/01/2026 to 19/01/2026\nScreening time morning 07:30 to 10:30\n\nNotes All India Net ( OVIS) check and block',
    lastUpdated: '15/01/2026 10:30 AM'
  },
  {
    id: '2',
    name: 'Apollo Diagnostics',
    state: State.Maharashtra,
    status: 'Pending',
    detail: 'Primary care diagnostic facility with radiology services.',
    report: 'Inventory status report',
    contact: 'Anjali Sharma',
    phone: '+91 9876543211',
    volunteerGender: 'All',
    inHouse: '24 Hours',
    periodCount: '2',
    lastUpdated: '14/01/2026 02:15 PM'
  },
  {
    id: '3',
    name: 'Precision Labs',
    state: State.Gujarat,
    status: 'Completed',
    detail: 'Specialized testing lab for industrial safety and health.',
    report: 'Annual safety audit 2024',
    contact: 'Vikas Patel',
    phone: '+91 9876543212',
    lastUpdated: '10/01/2026 09:00 AM'
  }
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n1',
    title: 'Status Updated',
    message: 'Clinovi Research is now marked as Active.',
    timestamp: '2 mins ago',
    type: 'status_change',
    isRead: false
  },
  {
    id: 'n2',
    title: 'New Report Available',
    message: 'Weekly health screening report uploaded for Sunrise Clinical Lab.',
    timestamp: '1 hour ago',
    type: 'report_added',
    isRead: false
  }
];